// Generated by gencpp from file px4_msgs/VehicleThrustAccSetpoint.msg
// DO NOT EDIT!


#ifndef PX4_MSGS_MESSAGE_VEHICLETHRUSTACCSETPOINT_H
#define PX4_MSGS_MESSAGE_VEHICLETHRUSTACCSETPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_msgs
{
template <class ContainerAllocator>
struct VehicleThrustAccSetpoint_
{
  typedef VehicleThrustAccSetpoint_<ContainerAllocator> Type;

  VehicleThrustAccSetpoint_()
    : timestamp(0)
    , thrust_acc_sp(0.0)
    , rates_sp()
    , model_ff(0.0)
    , lead_information(0.0)  {
      rates_sp.assign(0.0);
  }
  VehicleThrustAccSetpoint_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , thrust_acc_sp(0.0)
    , rates_sp()
    , model_ff(0.0)
    , lead_information(0.0)  {
  (void)_alloc;
      rates_sp.assign(0.0);
  }



   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef float _thrust_acc_sp_type;
  _thrust_acc_sp_type thrust_acc_sp;

   typedef boost::array<float, 3>  _rates_sp_type;
  _rates_sp_type rates_sp;

   typedef float _model_ff_type;
  _model_ff_type model_ff;

   typedef float _lead_information_type;
  _lead_information_type lead_information;





  typedef boost::shared_ptr< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleThrustAccSetpoint_

typedef ::px4_msgs::VehicleThrustAccSetpoint_<std::allocator<void> > VehicleThrustAccSetpoint;

typedef boost::shared_ptr< ::px4_msgs::VehicleThrustAccSetpoint > VehicleThrustAccSetpointPtr;
typedef boost::shared_ptr< ::px4_msgs::VehicleThrustAccSetpoint const> VehicleThrustAccSetpointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator1> & lhs, const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.thrust_acc_sp == rhs.thrust_acc_sp &&
    lhs.rates_sp == rhs.rates_sp &&
    lhs.model_ff == rhs.model_ff &&
    lhs.lead_information == rhs.lead_information;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator1> & lhs, const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5872a8a2a7714255ea85f043e820058d";
  }

  static const char* value(const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5872a8a2a7714255ULL;
  static const uint64_t static_value2 = 0xea85f043e820058dULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_msgs/VehicleThrustAccSetpoint";
  }

  static const char* value(const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint64 timestamp        # time since system start (microseconds)\n"
"\n"
"\n"
"\n"
"float32 thrust_acc_sp          # thrust acceleration setpoint along the thrust axis, like amostly Z body axis.\n"
"\n"
"float32[3] rates_sp\n"
"\n"
"float32 model_ff\n"
"float32 lead_information\n"
"\n"
;
  }

  static const char* value(const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.thrust_acc_sp);
      stream.next(m.rates_sp);
      stream.next(m.model_ff);
      stream.next(m.lead_information);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleThrustAccSetpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_msgs::VehicleThrustAccSetpoint_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "thrust_acc_sp: ";
    Printer<float>::stream(s, indent + "  ", v.thrust_acc_sp);
    s << indent << "rates_sp[]" << std::endl;
    for (size_t i = 0; i < v.rates_sp.size(); ++i)
    {
      s << indent << "  rates_sp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rates_sp[i]);
    }
    s << indent << "model_ff: ";
    Printer<float>::stream(s, indent + "  ", v.model_ff);
    s << indent << "lead_information: ";
    Printer<float>::stream(s, indent + "  ", v.lead_information);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_MSGS_MESSAGE_VEHICLETHRUSTACCSETPOINT_H
