# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from px4_msgs/VehicleThrustAccSetpoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehicleThrustAccSetpoint(genpy.Message):
  _md5sum = "5872a8a2a7714255ea85f043e820058d"
  _type = "px4_msgs/VehicleThrustAccSetpoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
uint64 timestamp        # time since system start (microseconds)



float32 thrust_acc_sp          # thrust acceleration setpoint along the thrust axis, like amostly Z body axis.

float32[3] rates_sp

float32 model_ff
float32 lead_information

"""
  __slots__ = ['timestamp','thrust_acc_sp','rates_sp','model_ff','lead_information']
  _slot_types = ['uint64','float32','float32[3]','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,thrust_acc_sp,rates_sp,model_ff,lead_information

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleThrustAccSetpoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.thrust_acc_sp is None:
        self.thrust_acc_sp = 0.
      if self.rates_sp is None:
        self.rates_sp = [0.] * 3
      if self.model_ff is None:
        self.model_ff = 0.
      if self.lead_information is None:
        self.lead_information = 0.
    else:
      self.timestamp = 0
      self.thrust_acc_sp = 0.
      self.rates_sp = [0.] * 3
      self.model_ff = 0.
      self.lead_information = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Qf().pack(_x.timestamp, _x.thrust_acc_sp))
      buff.write(_get_struct_3f().pack(*self.rates_sp))
      _x = self
      buff.write(_get_struct_2f().pack(_x.model_ff, _x.lead_information))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.timestamp, _x.thrust_acc_sp,) = _get_struct_Qf().unpack(str[start:end])
      start = end
      end += 12
      self.rates_sp = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.model_ff, _x.lead_information,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Qf().pack(_x.timestamp, _x.thrust_acc_sp))
      buff.write(self.rates_sp.tostring())
      _x = self
      buff.write(_get_struct_2f().pack(_x.model_ff, _x.lead_information))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.timestamp, _x.thrust_acc_sp,) = _get_struct_Qf().unpack(str[start:end])
      start = end
      end += 12
      self.rates_sp = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 8
      (_x.model_ff, _x.lead_information,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_Qf = None
def _get_struct_Qf():
    global _struct_Qf
    if _struct_Qf is None:
        _struct_Qf = struct.Struct("<Qf")
    return _struct_Qf
